extends GutTest

## tb66 Pass E — **the committed shard map, and the four properties that make it safe to run a gate
## from.**
##
## The map itself is generated by `tools/pack_shards.gd` and committed. This asserts the things that
## would silently break a sharded gate rather than fail it loudly: a file assigned to nobody, the
## corpus split across shards, or an assignment that moves between runs.


func _map() -> Dictionary:
	return ShardMap.load_map()


func _all_test_files(root: String = "res://test") -> Array[String]:
	var found: Array[String] = []
	var dir := DirAccess.open(root)
	if dir == null:
		return found
	dir.list_dir_begin()
	var name: String = dir.get_next()
	while name != "":
		var path: String = "%s/%s" % [root, name]
		if dir.current_is_dir():
			found.append_array(_all_test_files(path))
		elif name.begins_with("test_") and name.ends_with(".gd"):
			found.append(path)
		name = dir.get_next()
	dir.list_dir_end()
	return found


## **Every test file lands in exactly one shard.** A file in no shard is never run, and a sharded
## gate would go green having silently skipped it — which is the worst outcome available here and
## indistinguishable from success without this test.
##
## **Regenerate with `tools/pack_shards.gd` when this fails.** It failing is the intended
## signal that a file was added since the map was packed, not a defect in the map.
func test_every_test_file_is_assigned_to_exactly_one_shard() -> void:
	var shards: Dictionary = _map()
	assert_false(shards.is_empty(), "the shard map must be generated and committed")
	if shards.is_empty():
		return

	var assigned: Array[String] = ShardMap.assigned_files(shards)
	var counts: Dictionary = {}
	for path: String in assigned:
		counts[path] = int(counts.get(path, 0)) + 1

	var missing: Array[String] = []
	for path: String in _all_test_files():
		if not counts.has(path):
			missing.append(path)
	var doubled: Array[String] = []
	for path: String in counts:
		if int(counts[path]) > 1:
			doubled.append(path)

	gut.p("%d files assigned across %d shards" % [assigned.size(), shards.size()])
	assert_eq(
		missing,
		[] as Array[String],
		(
			"unassigned files would be silently skipped by a sharded gate — regenerate with "
			+ "tools/pack_shards.gd:\n%s" % "\n".join(missing)
		)
	)
	assert_eq(doubled, [] as Array[String], "a file in two shards is run twice and counted twice")


## **The corpus readers are together, in shard 0.** Splitting them means more than one shard draws
## its own `BoutCorpus` sample — at the measured `p` that is up to nine extra missions played for
## nothing, and it would also make the gate's completion report ambiguous about which draw it
## describes.
func test_every_corpus_reader_is_in_the_corpus_shard() -> void:
	var shards: Dictionary = _map()
	if shards.is_empty():
		return

	var strays: Array[String] = []
	for path: String in SuiteTier.CORPUS_READERS:
		var shard: int = ShardMap.shard_for(path, shards)
		if shard != ShardMap.CORPUS_SHARD:
			strays.append("%s is in shard %d" % [path, shard])

	assert_eq(
		strays,
		[] as Array[String],
		(
			"a split corpus means more than one draw per gate — the one property Pass E's "
			+ "packing exists to hold:\n%s" % "\n".join(strays)
		)
	)


## **The non-corpus shards are balanced.** Nothing here is optimal packing — the makespan is the
## corpus shard, not the packing — but a shard carrying twice its neighbours would mean the packer
## silently stopped working, and the profile drifting is exactly how that happens.
##
## Asserted as a spread rather than a target, because the target moves whenever the suite does.
func test_the_non_corpus_shards_are_within_a_reasonable_spread() -> void:
	var shards: Dictionary = _map()
	if shards.is_empty():
		return
	var profile: Dictionary = _profile_costs()

	var loads: Array[float] = []
	for index: String in shards:
		if int(index) == ShardMap.CORPUS_SHARD:
			continue
		var total := 0.0
		for path: Variant in shards[index]:
			total += float(profile.get(String(path), ShardMap.UNKNOWN_FILE_COST))
		loads.append(total)

	loads.sort()
	var lightest: float = loads[0]
	var heaviest: float = loads[loads.size() - 1]
	gut.p("non-corpus shard loads: %.1f s to %.1f s" % [lightest, heaviest])
	assert_lt(
		heaviest,
		lightest * 2.0,
		"the heaviest non-corpus shard should not be twice the lightest — repack if it is"
	)


## **A file the profile has never seen is charged, not assumed free.** Treating an unknown as zero
## puts it wherever the packer had room and lets a shard grow a tail nobody planned for — and a new
## test file is precisely the case where nobody has a measurement yet.
func test_an_unmeasured_file_is_charged_the_conservative_default() -> void:
	assert_gt(ShardMap.UNKNOWN_FILE_COST, 0.0, "an unknown file must not be treated as free")

	var profile: Dictionary = _profile_costs()
	var unmeasured: Array[String] = []
	for path: String in ShardMap.assigned_files():
		if not profile.has(path):
			unmeasured.append(path)

	# Not an error — it is the normal case after adding a file. Reported so the packer's input is
	# visible rather than assumed complete.
	gut.p(
		(
			"%d assigned file(s) have no profile row and were packed at %.1f s each: %s"
			% [unmeasured.size(), ShardMap.UNKNOWN_FILE_COST, ", ".join(unmeasured)]
		)
	)
	assert_true(true, "reported rather than gated — see the note above")


# --- tb67 Pass B3: the fast map, guarded the same way -----------------------------------


## **Every non-bout file lands in exactly one fast shard.** Identical stakes to the full map: a file
## in no shard is never run and the gate goes green having skipped it. A second committed artifact
## with no guard is the thing B3 exists to prevent, so this is the same check, not a lighter one.
func test_every_non_bout_file_is_assigned_to_exactly_one_fast_shard() -> void:
	var shards: Dictionary = ShardMap.load_map(ShardMap.FAST_MAP_PATH)
	assert_false(shards.is_empty(), "the fast shard map must be generated and committed")
	if shards.is_empty():
		return

	var assigned: Array[String] = ShardMap.assigned_files(shards)
	var counts: Dictionary = {}
	for path: String in assigned:
		counts[path] = int(counts.get(path, 0)) + 1

	var missing: Array[String] = []
	for path: String in _all_test_files():
		if path in SuiteTier.BOUT_FILES:
			continue
		if not counts.has(path):
			missing.append(path)
	var doubled: Array[String] = []
	for path: String in counts:
		if int(counts[path]) > 1:
			doubled.append(path)

	gut.p("%d non-bout files assigned across %d fast shards" % [assigned.size(), shards.size()])
	assert_eq(
		missing,
		[] as Array[String],
		(
			"unassigned files would be silently skipped by a sharded fast gate — regenerate with "
			+ "tools/pack_shards.gd:\n%s" % "\n".join(missing)
		)
	)
	assert_eq(doubled, [] as Array[String], "a file in two shards is run twice and counted twice")


## **No bout file is in the fast map.** They are removed rather than costed at zero, because a
## zero-costed file is still loaded and parsed by whichever shard holds it. This is also what makes
## the fast map's shard 0 an ordinary bin: every corpus reader is a bout file, so there is no draw
## to reserve a shard for.
func test_no_bout_file_is_in_the_fast_map() -> void:
	var shards: Dictionary = ShardMap.load_map(ShardMap.FAST_MAP_PATH)
	if shards.is_empty():
		return

	var strays: Array[String] = []
	for path: String in SuiteTier.BOUT_FILES:
		var shard: int = ShardMap.shard_for(path, shards)
		if shard >= 0:
			strays.append("%s is in fast shard %d" % [path, shard])

	assert_eq(
		strays,
		[] as Array[String],
		"a bout file in the fast map is work the fast gate does not do:\n%s" % "\n".join(strays)
	)


## **The two maps agree about the suite**, which is the property that makes one packer run worth
## insisting on. Their union is every test file and neither invents one — so a fast map packed from
## a staler profile than the full map cannot go unnoticed, which is the way two artifacts drift.
func test_the_two_maps_describe_the_same_suite() -> void:
	var full: Array[String] = ShardMap.assigned_files(ShardMap.load_map())
	var fast: Array[String] = ShardMap.assigned_files(ShardMap.load_map(ShardMap.FAST_MAP_PATH))
	if full.is_empty() or fast.is_empty():
		return

	var in_full: Dictionary = {}
	for path: String in full:
		in_full[path] = true

	var unknown: Array[String] = []
	for path: String in fast:
		if not in_full.has(path):
			unknown.append(path)

	assert_eq(
		unknown,
		[] as Array[String],
		"the fast map names files the full map does not — they were packed from different inputs"
	)
	assert_eq(
		full.size() - fast.size(),
		SuiteTier.BOUT_FILES.size(),
		(
			"the maps differ by exactly the bout files (%d full, %d fast, %d bout files)"
			% [full.size(), fast.size(), SuiteTier.BOUT_FILES.size()]
		)
	)


func _profile_costs() -> Dictionary:
	var parsed: Variant = JSON.parse_string(
		FileAccess.get_file_as_string("res://test/suite_profile.json")
	)
	var out: Dictionary = {}
	if parsed is Dictionary:
		for row: Dictionary in (parsed as Dictionary).get("files", []):
			out[String(row.get("path", ""))] = float(row.get("usec", 0)) / 1_000_000.0
	return out
